name: pydgrid
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - bokeh
  - numba
  - numpy
  - scipy
  - nbsphinx
  - IPython
  - ipykernel
  - requests
  - pandas
  - sphinx
  - sphinx_rtd_theme
  - qgrid
